# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            Rehan Chinoy
description:      'Personal blog and research portfolio'
url:              https://rehanchinoy.com/
baseurl:          https://rehanchinoy.com/

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5       
