# Dependencies
highlighter:      rouge

# Setup
title:            Rehan Chinoy
description:      'ML Engineer, UCLA alum'
url:              https://rehanchinoy.com/
baseurl:          ''

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5
