# Dependencies
highlighter:      rouge

# Setup
title:            Rehan Chinoy
description:      'ML Engineer, UCLA applied math and neuroscience'
url:              https://rehanchinoy.com/
baseurl:          https://rehanchinoy.com/

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5
