# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rehan Chinoy
tagline:          'A Jekyll theme'
description:      'A portfolio and blog site for UCLA student Rehan Chinoy'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          
