# Dependencies
highlighter:      rouge

# Setup
title:            Rehan Chinoy
description:      'UCLA undergrad studying neuroscience and math. I write and think about topics from psychology, philosophy, and other things (sometimes).'
url:              https://rehanchinoy.com/
baseurl:          https://rehanchinoy.com/

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5
