# Dependencies
highlighter:      rouge

# Setup
title:            Rehan Chinoy
description:      'Undergrad studying applied math and neuroscience at UCLA'
url:              https://rehanchinoy.com/
baseurl:          https://rehanchinoy.com/

author:
  name:           'Rehan Chinoy'
  url:            

paginate:         5
